/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_RESOURCES_FILES           69
#define MMAP_RESOURCES_CHECKSUM        0xF096

enum MMAP_RESOURCES_LISTS {
    MMAP_RESOURCES_BG_SHUTDOWN_A2I1 = 0,        /*!< bg_shutdown.a2i1 */
    MMAP_RESOURCES_IC_S_ASSISTANT_HINT_A2I1 = 1,        /*!< ic_s_assistant_hint.a2i1 */
    MMAP_RESOURCES_IC_APP_HOME_BOOK_SPNG = 2,        /*!< ic_app_home_book.spng */
    MMAP_RESOURCES_IC_APP_HOME_BUDDY_SPNG = 3,        /*!< ic_app_home_buddy.spng */
    MMAP_RESOURCES_IC_APP_HOME_CLOUD_SPNG = 4,        /*!< ic_app_home_cloud.spng */
    MMAP_RESOURCES_IC_APP_HOME_DICTIONARY_SPNG = 5,        /*!< ic_app_home_dictionary.spng */
    MMAP_RESOURCES_IC_APP_HOME_MUSIC_SPNG = 6,        /*!< ic_app_home_music.spng */
    MMAP_RESOURCES_IC_APP_HOME_PHONE_SPNG = 7,        /*!< ic_app_home_phone.spng */
    MMAP_RESOURCES_IC_APP_HOME_PHOTO_SPNG = 8,        /*!< ic_app_home_photo.spng */
    MMAP_RESOURCES_IC_APP_HOME_RECORDING_SPNG = 9,        /*!< ic_app_home_recording.spng */
    MMAP_RESOURCES_IC_APP_HOME_SETTING_SPNG = 10,        /*!< ic_app_home_setting.spng */
    MMAP_RESOURCES_IC_APP_HOME_STUDY_SPNG = 11,        /*!< ic_app_home_study.spng */
    MMAP_RESOURCES_IC_APP_HOME_TASK_SPNG = 12,        /*!< ic_app_home_task.spng */
    MMAP_RESOURCES_IC_APP_HOME_TEACHER_SPNG = 13,        /*!< ic_app_home_teacher.spng */
    MMAP_RESOURCES_IC_APP_HOME_TRANSLATE_SPNG = 14,        /*!< ic_app_home_translate.spng */
    MMAP_RESOURCES_IC_APP_HOME_WALLPAPER_SPNG = 15,        /*!< ic_app_home_wallpaper.spng */
    MMAP_RESOURCES_IC_APP_TEST_FAIL_SPNG = 16,        /*!< ic_app_test_fail.spng */
    MMAP_RESOURCES_IC_APP_TEST_PASS_SPNG = 17,        /*!< ic_app_test_pass.spng */
    MMAP_RESOURCES_IC_S_STANDBY_BUBBLE_SPNG = 18,        /*!< ic_s_standby_bubble.spng */
    MMAP_RESOURCES_IC_S_STANDBY_CALENDAR_SPNG = 19,        /*!< ic_s_standby_calendar.spng */
    MMAP_RESOURCES_IC_S_STANDBY_CAT_SPNG = 20,        /*!< ic_s_standby_cat.spng */
    MMAP_RESOURCES_IC_S_STANDBY_MENU_SPNG = 21,        /*!< ic_s_standby_menu.spng */
    MMAP_RESOURCES_IC_S_TASK_CHECKED_SPNG = 22,        /*!< ic_s_task_checked.spng */
    MMAP_RESOURCES_IC_S_TASK_UNCHECKED_SPNG = 23,        /*!< ic_s_task_unchecked.spng */
    MMAP_RESOURCES_IC_S_WEATHER_00_SPNG = 24,        /*!< ic_s_weather_00.spng */
    MMAP_RESOURCES_IC_S_WEATHER_01_SPNG = 25,        /*!< ic_s_weather_01.spng */
    MMAP_RESOURCES_IC_S_WEATHER_02_SPNG = 26,        /*!< ic_s_weather_02.spng */
    MMAP_RESOURCES_IC_S_WEATHER_03_SPNG = 27,        /*!< ic_s_weather_03.spng */
    MMAP_RESOURCES_IC_S_WEATHER_04_SPNG = 28,        /*!< ic_s_weather_04.spng */
    MMAP_RESOURCES_IC_S_WEATHER_05_SPNG = 29,        /*!< ic_s_weather_05.spng */
    MMAP_RESOURCES_IC_S_WEATHER_06_SPNG = 30,        /*!< ic_s_weather_06.spng */
    MMAP_RESOURCES_IC_S_WEATHER_07_SPNG = 31,        /*!< ic_s_weather_07.spng */
    MMAP_RESOURCES_IC_S_WEATHER_08_SPNG = 32,        /*!< ic_s_weather_08.spng */
    MMAP_RESOURCES_IC_S_WEATHER_09_SPNG = 33,        /*!< ic_s_weather_09.spng */
    MMAP_RESOURCES_IC_S_WEATHER_10_SPNG = 34,        /*!< ic_s_weather_10.spng */
    MMAP_RESOURCES_IC_S_WEATHER_11_SPNG = 35,        /*!< ic_s_weather_11.spng */
    MMAP_RESOURCES_IC_S_WEATHER_12_SPNG = 36,        /*!< ic_s_weather_12.spng */
    MMAP_RESOURCES_IC_S_WEATHER_13_SPNG = 37,        /*!< ic_s_weather_13.spng */
    MMAP_RESOURCES_IC_S_WEATHER_14_SPNG = 38,        /*!< ic_s_weather_14.spng */
    MMAP_RESOURCES_IC_S_WEATHER_15_SPNG = 39,        /*!< ic_s_weather_15.spng */
    MMAP_RESOURCES_IC_S_WEATHER_16_SPNG = 40,        /*!< ic_s_weather_16.spng */
    MMAP_RESOURCES_IC_S_WEATHER_17_SPNG = 41,        /*!< ic_s_weather_17.spng */
    MMAP_RESOURCES_IC_S_WEATHER_18_SPNG = 42,        /*!< ic_s_weather_18.spng */
    MMAP_RESOURCES_IC_S_WEATHER_19_SPNG = 43,        /*!< ic_s_weather_19.spng */
    MMAP_RESOURCES_IC_S_WEATHER_20_SPNG = 44,        /*!< ic_s_weather_20.spng */
    MMAP_RESOURCES_IC_S_WEATHER_21_SPNG = 45,        /*!< ic_s_weather_21.spng */
    MMAP_RESOURCES_IC_S_WEATHER_22_SPNG = 46,        /*!< ic_s_weather_22.spng */
    MMAP_RESOURCES_IC_S_WEATHER_23_SPNG = 47,        /*!< ic_s_weather_23.spng */
    MMAP_RESOURCES_IC_S_WEATHER_24_SPNG = 48,        /*!< ic_s_weather_24.spng */
    MMAP_RESOURCES_IC_S_WEATHER_25_SPNG = 49,        /*!< ic_s_weather_25.spng */
    MMAP_RESOURCES_IC_S_WEATHER_26_SPNG = 50,        /*!< ic_s_weather_26.spng */
    MMAP_RESOURCES_IC_S_WEATHER_27_SPNG = 51,        /*!< ic_s_weather_27.spng */
    MMAP_RESOURCES_IC_S_WEATHER_28_SPNG = 52,        /*!< ic_s_weather_28.spng */
    MMAP_RESOURCES_IC_S_WEATHER_29_SPNG = 53,        /*!< ic_s_weather_29.spng */
    MMAP_RESOURCES_IC_S_WEATHER_30_SPNG = 54,        /*!< ic_s_weather_30.spng */
    MMAP_RESOURCES_IC_S_WEATHER_301_SPNG = 55,        /*!< ic_s_weather_301.spng */
    MMAP_RESOURCES_IC_S_WEATHER_302_SPNG = 56,        /*!< ic_s_weather_302.spng */
    MMAP_RESOURCES_IC_S_WEATHER_31_SPNG = 57,        /*!< ic_s_weather_31.spng */
    MMAP_RESOURCES_IC_S_WEATHER_32_SPNG = 58,        /*!< ic_s_weather_32.spng */
    MMAP_RESOURCES_IC_S_WEATHER_33_SPNG = 59,        /*!< ic_s_weather_33.spng */
    MMAP_RESOURCES_IC_S_WEATHER_34_SPNG = 60,        /*!< ic_s_weather_34.spng */
    MMAP_RESOURCES_IC_S_WEATHER_35_SPNG = 61,        /*!< ic_s_weather_35.spng */
    MMAP_RESOURCES_IC_S_WEATHER_49_SPNG = 62,        /*!< ic_s_weather_49.spng */
    MMAP_RESOURCES_IC_S_WEATHER_53_SPNG = 63,        /*!< ic_s_weather_53.spng */
    MMAP_RESOURCES_IC_S_WEATHER_54_SPNG = 64,        /*!< ic_s_weather_54.spng */
    MMAP_RESOURCES_IC_S_WEATHER_55_SPNG = 65,        /*!< ic_s_weather_55.spng */
    MMAP_RESOURCES_IC_S_WEATHER_56_SPNG = 66,        /*!< ic_s_weather_56.spng */
    MMAP_RESOURCES_IC_S_WEATHER_57_SPNG = 67,        /*!< ic_s_weather_57.spng */
    MMAP_RESOURCES_IC_S_WEATHER_58_SPNG = 68,        /*!< ic_s_weather_58.spng */
};
