"""Two-theme UI fonts, rasterized directly from OFL outline fonts at native sizes.
Only this UI's subset is embedded in the app; no original font partition writes.
"""
from functools import lru_cache
import hashlib
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, __version__ as pillow_version
from fontTools.ttLib import TTFont

root=Path(__file__).resolve().parents[1]
fontdir=root/'use_font/ui-themes'
sources=('SourceHanSansCN-Medium.otf','LXGWWenKaiGBScreen.ttf')
sizes=(18,20,22,25,28,30)
def characters():
    paths=[root/'main/ui_demo.cc',*sorted((root/'main/ui').glob('*.h')),*sorted((root/'main/ui').glob('*.cc'))]
    return sorted(set(chr(n) for n in range(32,127))|{c for p in paths for c in p.read_text() if ord(c)>127},key=ord)
@lru_cache(maxsize=12)
def outline(size,theme=0):
    return ImageFont.truetype(str(fontdir/sources[theme]),size,layout_engine=ImageFont.Layout.BASIC)
@lru_cache(maxsize=8192)
def make_glyph(c,size,theme=0):
    font=outline(size,theme)
    x0,y0,x1,y1=font.getbbox(c,anchor='ls')
    w,h=x1-x0,y1-y0
    if w and h:
        im=Image.new('L',(w,h))
        ImageDraw.Draw(im).text((-x0,-y0),c,font=font,anchor='ls',fill=255)
        pixels=bytes(min(3,(v+42)//85)*85 for v in im.tobytes())
    else:pixels=b''
    return w,h,x0,-y1,round(font.getlength(c)),pixels
@lru_cache(maxsize=12)
def metrics(size,theme=0):
    top=bottom=0
    for c in characters():
        _,h,_,y,_,_=make_glyph(c,size,theme)
        top=max(top,y+h);bottom=min(bottom,y)
    return top-bottom+2,-bottom+1
def build():
    chars=characters()
    for source in sources:
        with TTFont(fontdir/source) as font:
            missing=[c for c in chars if ord(c) not in font.getBestCmap()]
            if missing:raise ValueError((source,'missing glyphs',missing))
    out=['/* Generated by host/build_ui_fonts.py. OFL notices: use_font/ui-themes/. */','#include "lvgl.h"']
    for theme in (0,1):
      for size in sizes:
        bitmap=bytearray();desc=['{0}']
        for c in chars:
            w,h,x,y,adv,pixels=make_glyph(c,size,theme);offset=len(bitmap)
            for start in range(0,len(pixels),4):
                byte=0
                for j,pixel in enumerate(pixels[start:start+4]):byte|=(pixel//85)<<(6-j*2)
                bitmap.append(byte)
            desc.append('{.bitmap_index=%d,.adv_w=%d,.box_w=%d,.box_h=%d,.ofs_x=%d,.ofs_y=%d}'%(offset,adv*16,w,h,x,y))
        suffix=('a' if theme==0 else 'b')+str(size)
        out.append('static const uint8_t bitmap%s[]={%s};'%(suffix,','.join(map(str,bitmap))))
        out.append('static const lv_font_fmt_txt_glyph_dsc_t glyphs%s[]={%s};'%(suffix,','.join(desc)))
        out.append('static const uint16_t unicode%s[]={%s};'%(suffix,','.join(str(ord(c)-32) for c in chars)))
        out.append('static const lv_font_fmt_txt_cmap_t cmap%s[]={ {.range_start=32,.range_length=%d,.glyph_id_start=1,.unicode_list=unicode%s,.list_length=%d,.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY} };'%(suffix,ord(chars[-1])-31,suffix,len(chars)))
        out.append('static const lv_font_fmt_txt_dsc_t dsc%s={.glyph_bitmap=bitmap%s,.glyph_dsc=glyphs%s,.cmaps=cmap%s,.cmap_num=1,.bpp=2,.bitmap_format=0};'%(suffix,suffix,suffix,suffix))
        height,baseline=metrics(size,theme)
        out.append('const lv_font_t ui_font_%s={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=%d,.base_line=%d,.dsc=&dsc%s};'%(suffix,height,baseline,suffix))
    (root/'main/ui_demo_fonts.c').write_text('\n'.join(out)+'\n')
    advances=[]
    for theme in (0,1):
      for size in sizes:
        advances.append('{'+','.join(str(make_glyph(c,size,theme)[4]) for c in chars)+'}')
    header='''// Generated from the exact UI font source, shared by host and device.
#pragma once
#include <cstdint>
#include <algorithm>
namespace paper {
inline constexpr uint32_t kCodepoints[]={%s};
inline constexpr uint8_t kAdvances[][ %d ]={%s};
inline int FontIndex(int size){return size<=18?0:size<=20?1:size<=22?2:size<=25?3:size<=28?4:5;}
inline int Advance(uint32_t cp,int size,int theme){
 const auto* end=kCodepoints+sizeof(kCodepoints)/sizeof(kCodepoints[0]);
 const auto* p=std::lower_bound(kCodepoints,end,cp);
 return p==end||*p!=cp?size:kAdvances[(theme?6:0)+FontIndex(size)][p-kCodepoints];
}
}
'''%(','.join(str(ord(c)) for c in chars),len(chars),','.join(advances))
    (root/'main/ui/font_metrics.h').write_text(header)
    report={'pillow':pillow_version,'sizes':list(sizes),'bpp':2,'glyphs_per_font':len(chars),
            'files':{name:hashlib.sha256((fontdir/name).read_bytes()).hexdigest() for name in sources}}
    (fontdir/'build-manifest.json').write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps(report,indent=2))
if __name__=='__main__':build()
