"""Generate a tiny, SD-independent MiSans subset for recovery and standby."""
import argparse, re
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

p=argparse.ArgumentParser();p.add_argument('font',type=Path);a=p.parse_args()
root=Path(__file__).resolve().parents[1]
texts=''.join((root/'main/paper_shell'/f).read_text() for f in ('inkdesk_bridge.cc','maintenance.cc','standby.cc'))
chars=sorted(set(map(chr,range(32,127)))|set(re.findall(r'[\u3000-\u9fff\uff00-\uffef]',texts)),key=ord)
out=['/* Generated by host/build_rescue_fonts.py from local MiSans. */','#include "lvgl.h"']
for size in (18,22,32):
    font=ImageFont.truetype(str(a.font),size,layout_engine=ImageFont.Layout.BASIC)
    font.set_variation_by_axes([500])
    bitmap=[];desc=['{0}'];top=bottom=0
    for c in chars:
        x0,y0,x1,y1=font.getbbox(c,anchor='ls');w,h=x1-x0,y1-y0
        im=Image.new('L',(max(1,w),max(1,h)))
        ImageDraw.Draw(im).text((-x0,-y0),c,font=font,anchor='ls',fill=255)
        pixels=list(im.getdata()) if w*h else [];offset=len(bitmap)
        for pos in range(0,len(pixels),8):
            bitmap.append(sum((v>=128)<<(7-i) for i,v in enumerate(pixels[pos:pos+8])))
        desc.append('{.bitmap_index=%d,.adv_w=%d,.box_w=%d,.box_h=%d,.ofs_x=%d,.ofs_y=%d}'%(offset,round(font.getlength(c)*16),w,h,x0,-y1))
        top=max(top,-y0);bottom=max(bottom,y1)
    s=str(size)
    out.extend([
      'static const uint8_t bitmap%s[]={%s};'%(s,','.join(map(str,bitmap))),
      'static const lv_font_fmt_txt_glyph_dsc_t glyphs%s[]={%s};'%(s,','.join(desc)),
      'static const uint16_t unicode%s[]={%s};'%(s,','.join(str(ord(c)-32) for c in chars)),
      'static const lv_font_fmt_txt_cmap_t cmap%s[]={ {.range_start=32,.range_length=%d,.glyph_id_start=1,.unicode_list=unicode%s,.list_length=%d,.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY} };'%(s,ord(chars[-1])-31,s,len(chars)),
      'static const lv_font_fmt_txt_dsc_t dsc%s={.glyph_bitmap=bitmap%s,.glyph_dsc=glyphs%s,.cmaps=cmap%s,.cmap_num=1,.bpp=1};'%(s,s,s,s),
      'const lv_font_t paper_rescue_%s={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=%d,.base_line=%d,.dsc=&dsc%s};'%(s,top+bottom+2,bottom+1,s)])
    print(size,len(chars),len(bitmap))
(root/'main/paper_shell/rescue_fonts.c').write_text('\n'.join(out)+'\n')
