"""Reproducible, bounded font experiment. lv_font_conv pinned to 1.5.3.
Lab assets are separate from UI/reader fonts; no existing font partition changes.
"""
import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path
from build_ui_fonts import make_glyph, root, fontdir, sources
from fontTools.ttLib import TTCollection

SIZES = (16, 18, 20, 22, 24, 28, 32, 40)
PROFILES = {
    0: ('Pillow baseline / Source Han Sans Medium', fontdir/'SourceHanSansCN-Medium.otf', None),
    1: ('FreeType AUTO MONO / Source Han Sans Medium', fontdir/'SourceHanSansCN-Medium.otf', None),
    2: ('FreeType AUTO MONO / LXGW Neo XiHei Screen', fontdir/'candidates/LXGWNeoXiHeiScreen.ttf', None),
    3: ('FreeType AUTO MONO / WenQuanYi Micro Hei', fontdir/'candidates/WenQuanYiMicroHei-Regular.ttf', 0),
}
SAMPLE = '阅读美晨设置清窗边的光正在示例系统之继续，。（中文）'
CHARS = ''.join(sorted(set(SAMPLE + ''.join(chr(i) for i in range(32, 127))), key=ord))

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--converter', required=True, type=Path)
    a = p.parse_args()
    converter=a.converter.resolve()
    package=converter.parent/'package.json'
    if not package.is_file():raise ValueError('Cannot verify converter package.json')
    package_info=json.loads(package.read_text())
    if package_info.get('name')!='lv_font_conv' or package_info.get('version')!='1.5.3':
        raise ValueError('Legacy lab requires verified lv_font_conv 1.5.3')
    dest = root/'main/font_lab_assets'
    dest.mkdir(exist_ok=True)
    # lv_font_conv consumes a single TTF/OTF face. Keep the original TTC and
    # derive a reproducible regular-face TTF for the embedded experiment.
    ttc=fontdir/'candidates/wqy-microhei.ttc'
    extracted=fontdir/'candidates/WenQuanYiMicroHei-Regular.ttf'
    if ttc.exists() and (not extracted.exists() or extracted.stat().st_mtime < ttc.stat().st_mtime):
        TTCollection(ttc).fonts[0].save(extracted)
    for profile,(description,font,face) in PROFILES.items():
        for size in SIZES:
            name = f'lab_p{profile}_{size}'
            target = dest/(name+'.c')
            if profile in (1,2,3):
                cmd = [str(a.converter.resolve()), '--font', str(font),
                       '--symbols', CHARS, '--size', str(size), '--bpp', '1',
                       '--format', 'lvgl', '--no-compress', '--no-kerning',
                       '-o', str(target)]
                subprocess.run(cmd, check=True)
                # Absolute source paths are provenance in manifest, not generated C.
                code = target.read_text()
                target.write_text(re.sub(r'/\*\*.*?\*/', '/* Generated by build_font_lab.py; OFL font. */', code, count=1, flags=re.S))
            else:
                bitmap=[]; glyphs=['{0}']; top=bottom=0
                for c in CHARS:
                    w,h,x,y,advance,pixels=make_glyph(c,size,0)
                    offset=len(bitmap)
                    for j in range(0,len(pixels),8):
                        bitmap.append(sum((int(v>=128) << (7-k)) for k,v in enumerate(pixels[j:j+8])))
                    glyphs.append('{.bitmap_index=%d,.adv_w=%d,.box_w=%d,.box_h=%d,.ofs_x=%d,.ofs_y=%d}'%(offset,advance*16,w,h,x,y))
                    top=max(top,y+h);bottom=min(bottom,y)
                target.write_text('''/* Generated baseline: same Pillow 2-bit coverage, final threshold 128. */
#include "lvgl.h"
static const uint8_t bitmap[]={%s};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[]={%s};
static const uint16_t unicode[]={%s};
static const lv_font_fmt_txt_cmap_t cmap[]={ {.range_start=32,.range_length=%d,.glyph_id_start=1,.unicode_list=unicode,.list_length=%d,.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY} };
static const lv_font_fmt_txt_dsc_t dsc={.glyph_bitmap=bitmap,.glyph_dsc=glyphs,.cmaps=cmap,.cmap_num=1,.bpp=1};
const lv_font_t %s={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=%d,.base_line=%d,.dsc=&dsc};
'''%(','.join(map(str,bitmap)),','.join(glyphs),','.join(str(ord(c)-32) for c in CHARS),ord(CHARS[-1])-31,len(CHARS),name,top-bottom+2,-bottom+1))
    declarations='\n'.join(f'extern const lv_font_t lab_p{p}_{s};' for p in PROFILES for s in SIZES)
    rows=','.join('{'+','.join(f'&lab_p{p}_{s}' for s in SIZES)+'}' for p in PROFILES)
    (root/'main/ui/lab_fonts.h').write_text('''// Generated, dedicated font assets. Never silently rescale.
#pragma once
#include "lvgl.h"
extern "C" {
%s
}
inline const lv_font_t* LabFont(int profile,int size){
 static const lv_font_t* fonts[4][8]={%s};
 static const int sizes[]={16,18,20,22,24,28,32,40};
 if(profile<0||profile>3)return nullptr;
 for(int i=0;i<8;++i)if(sizes[i]==size)return fonts[profile][i];
 return nullptr;
}
'''%(declarations,rows))
    report={'converter':'lv_font_conv@'+package_info['version'],'converter_sha256':hashlib.sha256(converter.read_bytes()).hexdigest(),'sizes':SIZES,'characters':CHARS,
            'profiles':{str(p):d for p,(d,_,_) in PROFILES.items()},
            'font_sha256':{str(p):hashlib.sha256(font.read_bytes()).hexdigest() for p,(_,font,_) in PROFILES.items()},
            'files':{f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(dest.glob('*.c'))}}
    (fontdir/'font-lab-manifest.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
    print('Generated 32 bounded native-size experiment fonts')

if __name__=='__main__':main()
