"""Build firmware-pinned SHA256 block proofs without changing any PGF bytes."""
from pathlib import Path
import argparse,hashlib,struct,zlib
p=argparse.ArgumentParser();p.add_argument('fonts',type=Path);p.add_argument('out',type=Path);p.add_argument('header',type=Path);a=p.parse_args()
entries=[];a.out.mkdir(parents=True,exist_ok=True)
for name in [f'misans-{weight}-{px}.pgf' for weight in (400,500,700) for px in range(16,41)]:
    data=(a.fonts/name).read_bytes();h=data[:80]
    assert h[:4]==b'PGF1' and zlib.crc32(h[:76])==struct.unpack_from('<I',h,76)[0]
    count,_,offset=struct.unpack_from('<III',h,12);length=struct.unpack_from('<I',h,64)[0]
    assert offset==80+count*24 and len(data)==offset+length
    assert zlib.crc32(data[80:offset])==struct.unpack_from('<I',h,60)[0]
    assert zlib.crc32(data[offset:])==struct.unpack_from('<I',h,68)[0]
    assert not struct.unpack_from('<I',h,72)[0]&0x80000000
    previous=end=0
    for cp,at,n,advance,w,height,left,top in struct.iter_unpack('<IIIiHHhh',data[80:offset]):
        assert previous<cp<=0x10ffff and not 0xd800<=cp<=0xdfff
        assert at==end and n==(w*height+3)//4 and w<=96 and height<=96
        assert 0<=advance<=96*64 and -96<=left<=96 and -96<=top<=96
        previous,end=cp,at+n
    assert end==length
    proof=b'PFV2'+struct.pack('<III',2048,len(data),offset)+h+hashlib.sha256(data).digest()+hashlib.sha256(data[80:offset]).digest()
    proof+=b''.join(hashlib.sha256(data[i:i+2048]).digest() for i in range(offset,len(data),2048))
    target=a.out/(name+'.pfv2');target.write_bytes(proof)
    entries.append('    {"paper/fonts/'+name+'", "'+hashlib.sha256(proof).hexdigest()+'"},')
a.header.write_text('// Generated by tools/paper/build_font_proofs.py; reviewed PGF assets only.\n#pragma once\nnamespace paper {\nstruct FontProofAnchor { const char* path; const char* sha; };\ninline constexpr FontProofAnchor fontProofAnchors[] = {\n'+'\n'.join(entries)+'\n};\n}\n')
