// Generated by tools/paper/build_font_proofs.py; reviewed PGF assets only.
#pragma once
namespace paper {
struct FontProofAnchor { const char* path; const char* sha; };
inline constexpr FontProofAnchor fontProofAnchors[] = {
    {"paper/fonts/misans-400-18.pgf", "74c537ffadca505cb341c6fc17f8b25d2aaf3d122f60673abd1833a122e675ee"},
    {"paper/fonts/misans-400-26.pgf", "178b5f22f5898d010b46e7977dc554344c1622311f3d4d2dcd5fc9dba5e52e54"},
    {"paper/fonts/misans-500-32.pgf", "6263add0fd1781304f2011853c4c262173abd78e810ba4b68e3e77e6b91da8a0"},
};
}
