'use strict';
/* Exact raster samples from the same A8 bank as the native device. No browser-font impostors. */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const ALG=['M-A','M-N','N-A','L-A','N-N','O-N','FW'], AN=['自动对齐 · 黑白','字体自带 · 黑白','自动对齐 · 标准','轻微对齐','字体自带 · 标准','原轮廓 · 关闭微调','固件原样 · UI'];
const OUTPUTS=['mono','gray4'];
const FIELDS={font:'字体',px:'字号',algorithm:'算法',threshold:'墨色',weight:'字重',output:'输出方式',none:'不分列'};
const CONTENT=['common','dense','mixed','body'], CN=['常用字','密笔画','中英混排','连读正文'];
const defaults={font:'noto',px:22,algorithm:'N-A',weight:400,threshold:128,content:'common',inverse:false,input_bpp:8,output:'mono'};
const app={base:{...defaults},row:'algorithm',col:'px',rows:ALG.filter(a=>a!=='FW'),cols:[18,22,26],view:'matrix',zoom:1,
 selected:null,pinned:null,records:[],catalog:[],mode:'offline',token:'',generation:0,cache:new Map(),
 deviceAxis:2,deviceValues:[],deviceCards:[],connected:false};
const AXES=['font','px','algorithm','threshold','output'];
const AXIS_CODES=[0,1,2,3,10];
function note(s,err=false){$('#notice').textContent=s;$('#notice').classList.toggle('error',err);}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function button(text,value,handler,on=false,disabled=false){const b=document.createElement('button');b.type='button';b.textContent=text;b.dataset.value=String(value);b.setAttribute('aria-pressed',String(on));b.disabled=disabled;b.onclick=handler;return b;}
function group(id,values,name,handler,selected){const el=$(id);el.replaceChildren();for(const v of values)el.append(button(name(v),v,()=>handler(v),Array.isArray(selected)?selected.includes(v):selected===v));}
function font(id){return app.catalog.find(x=>x.id===id);}
function resolveWeight(id,requested){const weights=(font(id)?.weights||[]).map(Number);if(!weights.length)return null;if(weights.includes(Number(requested)))return Number(requested);return weights.reduce((best,w)=>Math.abs(w-requested)<Math.abs(best-requested)?w:best,weights[0]);}
function label(field,v){if(field==='output')return v==='gray4'?'四灰阶 · 待真机确认':'黑白 · 当前底座';if(field==='font')return font(v)?.short||v;if(field==='algorithm')return AN[ALG.indexOf(v)]+' / '+v;if(field==='px')return v+' px';if(field==='threshold')return ({144:'淡',128:'标准',112:'浓'})[v]+' / '+v;if(field==='weight')return ({400:'常规',500:'中等',700:'粗体'})[v]+' / '+v;return '固定';}
function available(s){return s.algorithm==='FW'?app.mode==='local':!!font(s.font)?.weights.includes(s.weight);}
function values(field){if(field==='font')return app.catalog.filter(c=>c.available).map(c=>c.id);if(field==='px')return Array.from({length:25},(_,i)=>i+16);if(field==='algorithm')return ALG;if(field==='output')return OUTPUTS;if(field==='threshold')return [144,128,112];if(field==='weight')return font(app.base.font)?.weights?.map(Number)||[];return ['fixed'];}
function initial(field){if(field==='font')return app.catalog.filter(c=>c.weights.includes(app.base.weight)).map(c=>c.id).slice(0,8);if(field==='px')return [18,22,26];if(field==='algorithm')return ALG.filter(a=>a!=='FW');if(field==='output')return OUTPUTS;if(field==='threshold')return [144,128,112];if(field==='weight')return [400,500,700];return ['fixed'];}
function recipe(s){return JSON.stringify(s,Object.keys(defaults));}
function valid(s){return s&&typeof s==='object'&&[8,9].includes(Object.keys(s).length)&&app.catalog.some(c=>c.id===s.font)&&Number.isInteger(s.px)&&s.px>=16&&s.px<=40&&ALG.includes(s.algorithm)&&[400,500,700].includes(s.weight)&&[112,128,144].includes(s.threshold)&&CONTENT.includes(s.content)&&typeof s.inverse==='boolean'&&[2,4,8].includes(s.input_bpp)&&(!s.output||OUTPUTS.includes(s.output));}
async function api(path,data){if(app.mode!=='local')throw Error('当前是离线样本版。双击「启动试验台.command」可读取本机字体并连接真机。');const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-FontBench-Token':app.token},body:JSON.stringify(data||{})});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||'请求失败');return d;}
const crcTable=Array.from({length:256},(_,i)=>{let c=i;for(let j=0;j<8;j++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);return c>>>0;});
function crc32(bytes){let crc=0xffffffff;for(const b of bytes)crc=crcTable[(crc^b)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}
function decodeTile(b64,tag){const data=Uint8Array.from(atob(b64),c=>c.charCodeAt(0)),v=new DataView(data.buffer);if(data.length<32||String.fromCharCode(...data.slice(0,8))!=='FB5TILE\0')throw Error('试字图片头损坏');const w=v.getUint32(8,true),h=v.getUint32(12,true),n=v.getUint32(16,true),crc=v.getUint32(20,true),actual=v.getUint32(24,true),kind=v.getUint32(28,true);if(actual!==tag||n!==data.length-32||!((kind===0&&w===208&&h===96)||(kind===1&&w===432&&h===224)))throw Error('试字图片规格或资源包不匹配');const raw=new Uint8Array(w*h);let i=32,j=0;while(i<data.length){let b=data[i++];if(b&128){let k=(b&127)+3;if(i>=data.length||j+k>raw.length)throw Error('试字图片损坏');raw.fill(data[i++],j,j+k);j+=k;}else{let k=b+1;if(i+k>data.length||j+k>raw.length)throw Error('试字图片损坏');raw.set(data.slice(i,i+k),j);i+=k;j+=k;}}if(j!==raw.length||crc32(raw)!==crc)throw Error('试字图片校验失败');return {raw,w,h,crc};}
function rawCanvas(raw,w,h,s){const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d'),im=ctx.createImageData(w,h),levels=(1<<s.input_bpp)-1;const pixels=new Uint8Array(w*h);for(let i=0;i<raw.length;i++){let q=s.input_bpp===8?raw[i]:Math.round(Math.round(raw[i]*levels/255)*255/levels);let ink=q>=s.threshold;let val=(s.inverse?ink:!ink)?255:0;if(s.output==='gray4'){const coverage=Math.floor((q*3+127)/255);val=(s.inverse?coverage:3-coverage)*85;}pixels[i]=val;im.data.set([val,val,val,255],i*4);}ctx.putImageData(im,0,0);return {canvas,crc:crc32(pixels)};}
async function render(s,kind='compact'){
 s={...defaults,...s};if(s.algorithm==='FW'&&!(s.font==='sourcehan'&&s.weight===500&&[18,20,22,25,28,30].includes(s.px)&&s.input_bpp===2&&s.threshold===128&&s.output==='mono'))throw Error('固件原样固定为原 UI 思源 Medium；点上方「与固件原样比较」使用精确规格。');
 const key=recipe(s)+kind;if(app.cache.has(key))return app.cache.get(key);
 const work=(async()=>{if(s.algorithm==='FW'&&app.mode!=='local')throw Error('固件原样需要本机版读取原仓库，或在真机上直接调用。此处不模拟。');if(!available(s))throw Error((font(s.font)?.name||s.font)+' 没有 '+s.weight+' 这个真实字重；请选择该字体已有字重。');
 if(app.mode==='local'){const d=await api('render',{spec:s,kind});const image=new Image();await new Promise((ok,no)=>{image.onload=ok;image.onerror=no;image.src='data:image/png;base64,'+d.png;});const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);return {canvas,meta:d.meta};}
 const bank=window.FONTBENCH_DEMO,fi=app.catalog.findIndex(c=>c.id===s.font),name=[fi,s.weight,s.px,ALG.indexOf(s.algorithm),CONTENT.indexOf(s.content),kind==='wide'?1:0].join('-')+'.t5';let tile=bank.tiles[name],padded=false;if(!tile&&kind==='wide'&&s.content!=='body'){tile=bank.tiles[name.replace('-1.t5','-0.t5')];padded=true;}if(!tile)throw Error('本页没有这款字体的离线样本，请启动本机版读取源文件。');
 const t=decodeTile(tile,bank.manifest.bundle_tag);if(padded){const a=new Uint8Array(432*224);for(let y=0;y<t.h;y++)a.set(t.raw.slice(y*t.w,(y+1)*t.w),y*432);t.raw=a;t.w=432;t.h=224;t.crc=crc32(a);}const res=rawCanvas(t.raw,t.w,t.h,s),source=font(s.font).faces.find(f=>Math.round(f.axes?.wght||f.weight)===s.weight);
 return {canvas:res.canvas,meta:{spec:{...s},source,requested_px:s.px,resolved_px:s.px,sample_id:`${bank.manifest.bundle_tag}:${name}:${s.threshold}:${s.input_bpp}:${s.inverse?1:0}:${s.output}`,master_crc32:t.crc,region_crc32:res.crc,resolved_ok:true,fallback_used:false,output_bpp:s.output==='gray4'?2:1,display_mode:s.output,physical_quality:'NOT_PROVEN',threshold_effective:s.output==='mono'&&!s.algorithm.startsWith('M-')}};
 })();app.cache.set(key,work);while(app.cache.size>256)app.cache.delete(app.cache.keys().next().value);try{return await work;}catch(e){app.cache.delete(key);throw e;}
}
function allControls(){
 group('#fontButtons',app.catalog.map(c=>c.id),id=>(font(id).available?'':'○ ')+font(id).short,v=>set('font',v),app.base.font);
 for(const b of $$('#fontButtons button')){b.title=font(b.dataset.value).name+' · '+(font(b.dataset.value).weights.join('/')||'尚未载入');b.classList.toggle('missing',!font(b.dataset.value).available);}
 $('#fontCount').textContent=app.catalog.filter(c=>c.available).length+' / '+app.catalog.length+' 已载入';
 $('#fontNote').textContent=(font(app.base.font)?.note||'')+' 可用字重：'+(font(app.base.font)?.weights.join(' / ')||'等待源文件');
 group('#sizeButtons',values('px'),String,v=>set('px',v),app.base.px);
 group('#algorithmButtons',ALG,v=>AN[ALG.indexOf(v)],v=>set('algorithm',v),app.base.algorithm);
 $('#algorithmCode').textContent=app.base.algorithm;
 group('#outputButtons',OUTPUTS,v=>v==='mono'?'黑白':'四灰阶实验',v=>set('output',v),app.base.output);
 $('#outputHint').textContent=app.base.output==='gray4'?'同一 A8 字形 → 白、浅灰、深灰、黑。网页仅为数字预览；真机需按「启用灰阶」，还需肉眼验收。':'沿用当前黑白输出；原轮廓与优化方案都可以在这一模式下比较。';
 $('#algorithmHint').textContent=app.base.algorithm==='O-N'?'关闭字形微调与额外加粗，按原曲线描边。这是没有网格优化的基准；仍需转成屏幕像素。':app.base.algorithm==='FW'?'直接读取当前 UI 已有字库或由真机调用；固定原始尺寸、字重与阈值。原阅读器 MiSans 是另一条链路，本项不冒充它。':app.base.algorithm.startsWith('M-')?'直接生成黑白字形，已经没有中间灰色；墨色门槛和灰阶输出不会让它多出灰色。':'按所选规则对齐字形，保留 A8 覆盖率；最后由黑白／四灰阶按钮决定输出。';
 group('#weightButtons',values('weight'),v=>({400:'常规',500:'中等',700:'粗体'})[v],v=>set('weight',v),app.base.weight);
 for(const b of $$('#weightButtons button'))b.title='此真实字重可用';
 group('#toneButtons',values('threshold'),v=>({144:'淡',128:'标准',112:'浓'})[v],v=>set('threshold',v),app.base.threshold);
 for(const b of $$('#toneButtons button')){b.disabled=app.base.output==='gray4'||app.base.algorithm.startsWith('M-')||app.base.algorithm==='FW';b.title=b.disabled?'当前处理下此项不生效，已禁用':'';}
 group('#contentButtons',CONTENT,v=>CN[CONTENT.indexOf(v)],v=>set('content',v),app.base.content);
 group('#bppButtons',[8,4,2],v=>v+' bit',v=>set('input_bpp',v),app.base.input_bpp);
 $$('[data-inverse]').forEach(b=>b.setAttribute('aria-pressed',String(app.base.inverse===(b.dataset.inverse==='true'))));
 $('#sourceLimit').textContent=app.mode==='local'?'本机版：可直接读取仓库字库与 Mac 苹方/黑体。获取按钮只从已列明的官方来源下载，文件只保存在本机。':'离线样本版：已载入的样文可立即比较。增加字体时请启动本机版；不会访问网络或伪造其他字体。';
 group('#rowAxes',Object.keys(FIELDS).filter(x=>x!=='none'),v=>FIELDS[v],v=>axis('row',v),app.row);
 group('#colAxes',Object.keys(FIELDS),v=>FIELDS[v],v=>axis('col',v),app.col);
 group('#rowValues',values(app.row),v=>label(app.row,v),v=>toggle('rows',v),app.rows);
 group('#colValues',values(app.col),v=>label(app.col,v),v=>toggle('cols',v),app.cols);
 const active=[app.row,app.col];$('#matrixSummary').textContent=`${app.rows.length} 行 × ${app.cols.length} 列 · 只改变${active.filter(x=>x!=='none').map(x=>FIELDS[x]).join('和')} · 其余固定`;
 group('#deviceAxis',AXES,v=>'比'+FIELDS[v],v=>{app.deviceAxis=AXES.indexOf(v);initDevice();update();},AXES[app.deviceAxis]);
 $('#ratingCount').textContent=app.records.length;
}
function set(field,v){let resolvedNote='';if(field==='font'){const resolved=resolveWeight(v,app.base.weight);if(resolved===null)return note('这款字体没有可用样本，请先读取字体来源。',true);if(resolved!==app.base.weight)resolvedNote=`${font(v).short} 没有当前字重，已切换到 ${resolved}。`;}if(field==='weight'){const resolved=resolveWeight(app.base.font,v);if(resolved===null)return note('当前字体没有可用字重。',true);if(resolved!==Number(v))resolvedNote=`当前字体没有 ${v} 字重，已切换到 ${resolved}。`;v=resolved;}app.base={...defaults,...app.base,[field]:v};app.calibration=false;if(field==='algorithm'&&v==='FW')app.base={...app.base,font:'sourcehan',weight:500,input_bpp:2,threshold:128,output:'mono'};if(app.view==='matrix'){if(field===app.row)app.rows=[v];if(field===app.col)app.cols=[v];}
 if(app.view==='device'&&field===AXES[app.deviceAxis]){let vals=app.deviceValues;if(vals.includes(v)&&vals.length>1)vals.splice(vals.indexOf(v),1);else if(!vals.includes(v)){vals.push(v);if(vals.length>4)vals.shift();}}
 app.selected=null;update();if(resolvedNote)note(resolvedNote);}
function toggle(key,v){const vals=app[key];if(vals.includes(v)){if(vals.length===1)return note('至少保留一个比较值。');app[key]=vals.filter(x=>x!==v);}else {if((key==='rows'?app.cols.length:app.rows.length)*(vals.length+1)>256)return note('本屏最多 256 格，请减少另一个维度。',true);app[key]=values(key==='rows'?app.row:app.col).filter(x=>[...vals,v].includes(x));}update();}
function axis(which,v){if(which==='row'){if(v===app.col){app.col='none';app.cols=['fixed'];}app.row=v;app.rows=initial(v);if(!app.rows.length)app.rows=[app.base[v]];}else {if(v===app.row){return note('行和列请选择不同的变量。');}app.col=v;app.cols=initial(v);}update();}
async function card(s,container,kind='compact',selectable=true){const generation=app.generation;container.onclick=null;container.onkeydown=null;delete container.dataset.sampleId;delete container.dataset.crc;container.className='sample';const title=document.createElement('div');title.className='sample-title';title.textContent=(font(s.font)?.short||s.font)+' · '+s.px+' px';const sub=document.createElement('div');sub.className='sample-meta';sub.textContent=`${s.algorithm} / ${s.weight} / T${s.threshold}${s.inverse?' / 反白':''} / ${s.output==='gray4'?'四灰阶':'黑白'}`;container.append(title,sub);if(selectable){container.tabIndex=0;container.setAttribute('role','button');container.setAttribute('aria-label',title.textContent+' '+sub.textContent);}
 try{const result=await render(s,kind);if(generation!==app.generation)return;const shown=document.createElement('canvas');shown.width=result.canvas.width;shown.height=result.canvas.height;shown.getContext('2d').drawImage(result.canvas,0,0);container.append(shown);container.dataset.sampleId=result.meta.sample_id;container.dataset.crc=result.meta.region_crc32;const hint=document.createElement('small');hint.textContent=kind==='wide'?'同宽连读样文 · 原生像素':'同一段样文 · 原生像素';container.append(hint);
 const choose=()=>{app.selected={spec:{...s},meta:result.meta};$$('.sample.selected').forEach(x=>x.classList.remove('selected'));container.classList.add('selected');selection();};if(selectable){container.onclick=choose;container.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};}
 }catch(e){if(generation!==app.generation)return;container.classList.add('unavailable');const p=document.createElement('p');p.textContent=e.message;container.append(p);container.removeAttribute('role');container.removeAttribute('tabindex');}
}
async function drawMatrix(){const target=$('#matrix');target.style.setProperty('--cols',app.cols.length);target.classList.toggle('zoom2',app.zoom===2);target.replaceChildren();const header=document.createElement('div');header.className='matrix-row headers';header.append(Object.assign(document.createElement('strong'),{textContent:FIELDS[app.row]+' ↓ / '+FIELDS[app.col]+' →'}));for(const c of app.cols)header.append(Object.assign(document.createElement('strong'),{textContent:label(app.col,c)}));target.append(header);const jobs=[];for(const r of app.rows){const row=document.createElement('div');row.className='matrix-row';const name=document.createElement('strong');name.className='row-label';name.textContent=label(app.row,r);row.append(name);for(const c of app.cols){const s={...app.base,[app.row]:r};if(app.col!=='none')s[app.col]=c;const box=document.createElement('div');row.append(box);jobs.push(()=>card(s,box,app.base.content==='body'?'wide':'compact'));}target.append(row);} // Bounded parallelism protects FreeType/localhost and keeps first rows responsive.
 const gen=app.generation;let next=0;await Promise.all(Array.from({length:Math.min(4,jobs.length)},async()=>{while(next<jobs.length&&gen===app.generation)await jobs[next++]();}));}
function selection(){const s=app.selected?.spec;$('#selectedTitle').textContent=s?`${font(s.font)?.name} · ${s.px} px · ${label('weight',s.weight)}`:'点一个样本，就能固定或保存';$('#selectedMeta').textContent=s?`${s.algorithm} / 阈值 ${s.threshold} / 输入 ${s.input_bpp} bit → 输出 ${s.output==='gray4'?2:1} bit / CRC ${Number(app.selected.meta.region_crc32).toString(16).padStart(8,'0')}`:'';for(const id of ['pinSelected','prefer','thin','clog'])$('#'+id).disabled=!s;}
async function drawAB(){const gen=app.generation;$('#baselineCard').replaceChildren();$('#currentCard').replaceChildren();if(app.pinned)await card(app.pinned.spec,$('#baselineCard'),'wide');else $('#baselineCard').innerHTML='<div class="empty">还没有基准。<br>左侧选好条件，点「当前条件固定为 A」。</div>';if(gen!==app.generation)return;await card(app.base,$('#currentCard'),'wide');if(gen!==app.generation)return;$('#sameAB').disabled=!app.pinned;$('#abDifference').textContent=app.pinned?'A 保留完整配置，切换右侧字号、字体、墨色不会改变 A。':'';if(app.pinned){try{const [a,b]=await Promise.all([render(app.pinned.spec,'wide'),render(app.base,'wide')]);if(gen!==app.generation)return;if(a.meta.region_crc32===b.meta.region_crc32)$('#abDifference').textContent='这两个样本的最终数字像素完全相同。这是有效结果。';}catch(e){if(gen!==app.generation)return;$('#abDifference').textContent=e.message;}}}
function persist(){try{localStorage.setItem('fontbench5.records',JSON.stringify(app.records));localStorage.setItem('fontbench5.pinned',JSON.stringify(app.pinned));}catch(e){note('浏览器存储不可用，请导出记录保留。',true);}}
function addRecord(feedback,sample=app.selected){if(!sample?.meta?.resolved_ok)return note('请先选择一份已载入的样本。',true);app.records.push({schema:6,time:new Date().toISOString(),feedback,spec:{...sample.spec},sample_id:sample.meta.sample_id,source:sample.meta.source,region_crc32:sample.meta.region_crc32,resolved_ok:true,evidence:'browser-observation',physical_quality:'NOT_PROVEN',origin:'fontbench'});persist();allControls();note('已记录「'+feedback+'」。真机感受可另外记入设备优选。');drawHistory();}
function pin(sample){if(!sample?.meta?.resolved_ok)return note('请先选择一份真实样本。',true);app.pinned=JSON.parse(JSON.stringify(sample));persist();note('已固定基准 A；后续调整只改变候选。');update();}
function saveFile(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exported(all=false){return {schema:6,created_at:new Date().toISOString(),records:app.records.filter(r=>all||[5,6].includes(r.schema)&&r.feedback==='优选'),baseline:app.pinned,physical_quality:'各条记录按来源区分；网页观感未证明真机观感'};}
function drawHistory(){const target=$('#history');target.replaceChildren();if(!app.records.length){target.innerHTML='<div class="empty">优选会集中在这里。旧记录可直接导入，无需再打开旧 Lab。</div>';return;}for(const r of [...app.records].reverse()){const div=document.createElement('article');div.className='history-row';const original=r.original||r;const p=document.createElement('div');const h=document.createElement('strong');h.textContent=[5,6].includes(r.schema)?`${original.feedback} · ${font(original.spec?.font)?.short||original.spec?.font} ${original.spec?.px} px`:`历史 ${r.origin||'unknown'} · 保留原记录`;p.append(h);const pre=document.createElement('p');pre.textContent=[5,6].includes(r.schema)?`${original.spec.algorithm} / ${original.spec.weight} / T${original.spec.threshold} · ${original.evidence||'旧记录'} · ${original.time||''}`:'旧版样本身份可能不完整；不合并到当前排名。';p.append(pre);div.append(p);if(valid(original.spec))div.append(button('按此配置复看','restore',()=>{app.base={...defaults,...original.spec};app.selected=null;app.row='algorithm';app.col='none';app.rows=[app.base.algorithm];app.cols=['fixed'];switchView('matrix');}));target.append(div);}}
function importText(text){if(text.length>4*1024*1024)throw Error('最多导入 4 MB');let doc;try{doc=JSON.parse(text);}catch{doc=text.split(/\r?\n/).filter(x=>x.trim()).map(x=>JSON.parse(x));}const items=Array.isArray(doc)?doc:doc.records||[doc];if(items.length>5000)throw Error('最多导入 5000 条');let n=0;const seen=new Set(app.records.map(r=>JSON.stringify(r.original||r)));for(const r of items){if(!r||typeof r!=='object'||Array.isArray(r))throw Error('记录格式无效');const key=JSON.stringify(r.original||r);if(seen.has(key))continue;seen.add(key);const norm=[5,6].includes(r.schema)&&valid(r.spec)?r:{origin:r.schema===4||r.sample_id?'lab4':'lab3',eligible:false,original:r};app.records.push(norm);n++;}persist();update();note(`导入 ${n} 条；已有记录完整保留。`);}
function initDevice(){let field=AXES[app.deviceAxis],v=app.base[field];if(field==='font')app.deviceValues=app.catalog.filter(c=>c.weights.includes(app.base.weight)).map(c=>c.id).slice(0,4);else if(field==='px')app.deviceValues=[v-2,v,v+2,v+4].filter(x=>x>=16&&x<=40);else if(field==='algorithm')app.deviceValues=ALG.slice(0,4);else if(field==='output')app.deviceValues=OUTPUTS.slice();else app.deviceValues=[144,128,112];if(!app.deviceValues.includes(v)){app.deviceValues.push(v);if(app.deviceValues.length>4)app.deviceValues.shift();}}
function deviceSpecs(){const f=AXES[app.deviceAxis];let specs=app.deviceValues.map(v=>({...app.base,[f]:v}));if(app.pinned)specs=[app.pinned.spec,...specs.filter(s=>recipe(s)!==recipe(app.pinned.spec)).slice(0,3)];return specs.slice(0,4);}
async function drawDevice(){const canvas=$('#deviceCanvas'),ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,480,800);const data=Uint8Array.from(atob(window.FONTBENCH_DEMO.controls),c=>c.charCodeAt(0)),im=ctx.createImageData(480,800);for(let i=0;i<480*800;i++){const v=data[i>>3]&(128>>(i&7))?255:0;im.data.set([v,v,v,255],i*4);}ctx.putImageData(im,0,0);
 for(const c of window.FONTBENCH_DEMO.manifest.controls){let val=c.value;let cur=app.base[c.field];if(c.field==='font')val=app.catalog[c.value]?.id;if(c.field==='algorithm')val=ALG[c.value];if(c.field==='content')val=CONTENT[c.value];if(c.field==='inverse')val=!!c.value;if(c.field==='output')val=OUTPUTS[c.value];let on=c.field==='axis'?AXIS_CODES[app.deviceAxis]===val:c.field===AXES[app.deviceAxis]?app.deviceValues.includes(val):cur===val;if(on){const [x,y,w,h]=c.box,region=ctx.getImageData(x,y,w,h);for(let i=0;i<region.data.length;i+=4){region.data[i]=255-region.data[i];region.data[i+1]=region.data[i];region.data[i+2]=region.data[i];}ctx.putImageData(region,x,y);}}
 const specs=app.calibration?Array(4).fill({...app.base,output:'gray4'}):deviceSpecs(),positions=[[20,472],[248,472],[20,594],[248,594]],gen=app.generation;app.deviceCards=[];
 for(let i=0;i<specs.length;i++){const s=specs[i],[x,y]=positions[i];if(app.calibration){const value=[255,170,85,0][i];ctx.fillStyle=`rgb(${value},${value},${value})`;ctx.fillRect(x+2,y+24,208,96);ctx.fillStyle='black';ctx.font='14px monospace';ctx.fillText(['WHITE / 255','LIGHT / 170','DARK / 85','BLACK / 0'][i],x+4,y+16);continue;}ctx.fillStyle='black';ctx.font='12px monospace';ctx.fillText(`${app.pinned&&i===0?'A ':''}F${app.catalog.findIndex(c=>c.id===s.font)} ${s.px}px ${s.algorithm} W${s.weight} T${s.threshold}`,x+4,y+13);try{const res=await render(s);if(gen!==app.generation)return;ctx.drawImage(res.canvas,x+2,y+24);app.deviceCards.push({box:[x,y,212,122],spec:s,meta:res.meta});}catch(e){if(gen!==app.generation)return;ctx.font='15px sans-serif';ctx.fillText('缺少此字体 / 字重',x+14,y+53);ctx.fillText('此格不可评分',x+14,y+79);}}
 if(gen!==app.generation)return;
 const final=ctx.getImageData(0,0,480,800);for(let i=0;i<final.data.length;i+=4){const x=(i/4)%480,y=Math.floor(i/4/480);const gray=positions.some(([px,py],k)=>specs[k]?.output==='gray4'&&x>=px+2&&x<px+210&&y>=py+24&&y<py+120);const v=gray?Math.round(final.data[i]*3/255)*85:(final.data[i]>=128?255:0);final.data[i]=final.data[i+1]=final.data[i+2]=v;}ctx.putImageData(final,0,0);
}
async function deviceClick(e){const c=$('#deviceCanvas'),r=c.getBoundingClientRect(),x=(e.clientX-r.left)*480/r.width,y=(e.clientY-r.top)*800/r.height;const hit=window.FONTBENCH_DEMO.manifest.controls.find(o=>{const [a,b,w,h]=o.box;return x>=a&&x<a+w&&y>=b&&y<b+h;});if(hit){let {field,value}=hit;if(field==='axis'){app.deviceAxis=AXIS_CODES.indexOf(value);initDevice();return update();}if(field==='action'){if(value===0){if(!app.selected){const res=await render(app.base);app.selected={spec:{...app.base},meta:res.meta};}return pin(app.selected);}if(value===1){app.pinned=null;persist();return update();}if(value===2)return addRecord('优选');if(value===5&&!app.connected){app.calibration=!app.calibration;return update();}if(value>=3){if(!app.connected)return note('网页保持静态。连接真机后才能检验全刷 / 快刷的物理效果。');return run(async()=>{$('#deviceStatus').textContent=JSON.stringify(await api('device-control',{field:'action',value}),null,2);});}}if(field==='font')value=app.catalog[value].id;if(field==='algorithm')value=ALG[value];if(field==='content')value=CONTENT[value];if(field==='inverse')value=!!value;if(field==='output')value=OUTPUTS[value];return set(field,value);}const chosen=app.deviceCards.find(o=>{const [a,b,w,h]=o.box;return x>=a&&x<a+w&&y>=b&&y<b+h;});if(chosen){app.selected={spec:chosen.spec,meta:chosen.meta};selection();note('已选中 '+font(chosen.spec.font).short+' '+chosen.spec.px+' px');}}
function switchView(view){app.view=view;$$('[data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===view));for(const v of ['matrix','ab','device','history'])$('#'+v+'View').hidden=view!==v;if(view==='device')initDevice();update();}
function update(){app.generation++;allControls();selection();if(app.view==='matrix')drawMatrix();if(app.view==='ab')drawAB();if(app.view==='device')drawDevice();if(app.view==='history')drawHistory();}
async function run(fn){try{return await fn();}catch(e){note(e.message||String(e),true);}}
async function boot(){app.catalog=window.FONTBENCH_DEMO.manifest.catalog;try{app.records=JSON.parse(localStorage.getItem('fontbench5.records')||'[]');app.pinned=JSON.parse(localStorage.getItem('fontbench5.pinned')||'null');if(!Array.isArray(app.records))app.records=[];if(app.pinned&&!valid(app.pinned.spec))app.pinned=null;}catch{app.records=[];app.pinned=null;}
 if(location.protocol==='http:'||location.protocol==='https:'){try{const r=await fetch('/api/bootstrap');if(r.ok){const d=await r.json();if(d.mode==='local'){app.mode='local';app.token=d.token;app.catalog=d.catalog;$('#repoPath').value=d.repo;}}}catch{}}
 $$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-inverse]').forEach(b=>b.onclick=()=>set('inverse',b.dataset.inverse==='true'));

 $('#outlinePreset').onclick=()=>run(async()=>{app.base={...app.base,algorithm:'O-N',output:'mono',input_bpp:8,threshold:128};const r=await render(app.base,'wide');app.pinned={spec:{...app.base},meta:r.meta};app.base={...app.base,algorithm:'N-A'};persist();switchView('ab');note('左侧固定原轮廓；右侧切换算法。两边字体、字号和字重相同。');});
 $('#firmwarePreset').onclick=()=>{let px=[18,20,22,25,28,30].includes(app.base.px)?app.base.px:22;
  const spec={...defaults,font:'sourcehan',weight:500,px,input_bpp:2,algorithm:'FW',content:app.base.content,inverse:app.base.inverse};
  app.pinned={spec,meta:{resolved_ok:false,baseline_pending:true}};app.base={...spec,algorithm:'N-A',input_bpp:8};app.selected=null;persist();switchView('ab');note('A 直接使用原 UI 字库，B 使用同字号思源 Medium。载入仓库或连接真机后才能看到真实 A；规格缺失会明确提示。');};
 $('#grayPreset').onclick=()=>{app.base={...app.base,algorithm:app.base.algorithm==='FW'||app.base.algorithm.startsWith('M-')?'N-A':app.base.algorithm,input_bpp:8,threshold:128,output:'mono'};app.row='algorithm';app.rows=['O-N','N-A','L-A','N-N'];app.col='output';app.cols=OUTPUTS.slice();app.selected=null;app.calibration=false;switchView('matrix');note('每行同一份 A8 字形，左右只改变黑白／四灰阶输出；网页灰色是数字预览。');};
 $('#blocksPreset').onclick=()=>{switchView('device');app.calibration=true;update();note('四个实心色块用于真机能力验证。网页能显示四档，尚未证明墨水屏能显示。');};
 $('#armGray').onclick=()=>run(async()=>{const d=await api('device-control',{field:'action',value:6});app.connected=true;$('#deviceStatus').textContent=JSON.stringify(d,null,2);note('已启用本次开机的灰阶实验。继续点击「真机色块」；最终光学效果由你观察。');});
 $('#deviceBlocks').onclick=()=>run(async()=>{$('#deviceStatus').textContent=JSON.stringify(await api('device-control',{field:'action',value:5}),null,2);});
 $('#recoverGray').onclick=()=>run(async()=>{$('#deviceStatus').textContent=JSON.stringify(await api('device-control',{field:'action',value:7}),null,2);note('已请求关闭灰阶并恢复原显示模式；BUSY 未释放时会明确报错并停止。');});
  $('#reset').onclick=()=>{app.base={...defaults};app.row='algorithm';app.col='px';app.rows=ALG.filter(a=>a!=='FW');app.cols=[18,22,26];app.selected=null;initDevice();update();note('已恢复初筛条件。基准与历史记录保留。');};
 $('#selectAll').onclick=()=>{const v=values(app.row);if(v.length*app.cols.length>256)return note('超过 256 格，请减少列选项。',true);app.rows=v;update();};
 $('#commonSizes').onclick=()=>{if(app.row==='px')app.rows=[18,22,26];else if(app.col==='px')app.cols=[18,22,26];else {app.col='px';app.cols=[18,22,26];}update();};
 $('#oneX').onclick=()=>{app.zoom=1;$('#oneX').classList.add('on');$('#twoX').classList.remove('on');update();};$('#twoX').onclick=()=>{app.zoom=2;$('#oneX').classList.remove('on');$('#twoX').classList.add('on');update();note('2 倍只用于检查像素结构，最佳观感请用真机正常距离判断。');};
 $('#pinSelected').onclick=()=>pin(app.selected);$('#pinCurrent').onclick=()=>run(async()=>{const r=await render(app.base,'wide');pin({spec:{...app.base},meta:r.meta});});
 $('#unpin').onclick=()=>{app.pinned=null;persist();update();};$('#sameAB').onclick=()=>run(async()=>{const r=await render(app.base,'wide');addRecord('相同',{spec:{...app.base},meta:r.meta});app.records[app.records.length-1].baseline=app.pinned;persist();});
 $('#prefer').onclick=()=>addRecord('优选');$('#thin').onclick=()=>addRecord('太细');$('#clog').onclick=()=>addRecord('粘连');
 $('#exportResults').onclick=()=>saveFile('字体优选.json',JSON.stringify(exported(),null,2));$('#exportAll').onclick=()=>saveFile('字体全部记录.json',JSON.stringify(exported(true),null,2));
 $('#importHistory').onclick=()=>$('#historyFile').click();$('#historyFile').onchange=()=>run(async()=>{const f=$('#historyFile').files[0];if(f)importText(await f.text());$('#historyFile').value='';});
 $('#scan').onclick=()=>run(async()=>{note('正在读取指定目录中的真实字体…');const d=await api('scan',{repo:$('#repoPath').value,extra:$('#fontPath').value});app.catalog=d.catalog;app.cache.clear();app.pinned=null;persist();update();note('已载入 '+app.catalog.filter(c=>c.available).length+' 个字体条目。未载入的仍明确保留空位。');});
 $('#fetchFonts').onclick=()=>run(async()=>{note('正在从官方来源获取思源、鸿蒙、新晰黑；结果会逐项报告。');$('#fetchFonts').disabled=true;try{const d=await api('download-fonts');app.catalog=d.catalog;app.cache.clear();app.pinned=null;persist();update();note(Object.entries(d.results).map(([id,v])=>font(id).short+'：'+(v.error?'获取失败 '+v.error:'已载入')).join('；'));}finally{$('#fetchFonts').disabled=false;}});
 $('#downloadSD').onclick=()=>run(async()=>{$('#downloadSD').disabled=true;note('正在按已载入字体生成 SD 样本。生成完成后将下载；不会写入设备。');try{const d=await api('sd');location.href=d.url;note(`已生成 ${d.tiles} 张样本，包含：${d.fonts.join('、')}。复制 ZIP 内 inkdesk/fontbench 到 SD。`);}finally{$('#downloadSD').disabled=false;}});
 $('#connectDevice').onclick=()=>run(async()=>{const d=await api('device');app.connected=true;$('#deviceStatus').textContent=JSON.stringify(d,null,2);note('已读取设备状态；尚未发送画面。');});
 $('#sendDevice').onclick=()=>run(async()=>{note('正在通过原有 USB 服务应用参数…');const d=await api('device-apply',{spec:app.base,axis:AXIS_CODES[app.deviceAxis],values:app.deviceValues,pin:app.pinned});app.connected=true;$('#deviceStatus').textContent=JSON.stringify(d,null,2);note('设备已返回完成状态。请在屏上观察真实效果。');});
 $('#serverHistory').onclick=()=>run(async()=>{const d=await api('device-logs');for(const value of Object.values(d))if(value.text)importText(value.text);note(Object.entries(d).map(([k,v])=>k+(v.error?'：'+v.error:'：已读取')).join('；'));});
 $('#deviceCanvas').onclick=e=>run(()=>deviceClick(e));
 initDevice();update();note(app.mode==='local'?'本机试验台已启动。先比算法，再把行切换为「字体」；所有参数都能直接选。':'离线试字已准备好。双击「启动试验台.command」可自动读取本机与仓库里的更多黑体。');
 window.FontBench={app,render,rawCanvas,crc32,decodeTile,set,axis,toggle,update,importText,deviceSpecs,valid,switchView,ALG,defaults};
}
boot();
