#!/usr/bin/env python3
"""Generate compile-time PAPER constants. --check refuses stale outputs; no runtime JSON."""
import argparse,hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def expected():
    raw=(ROOT/'design-tokens/effective-tokens.json').read_bytes();d=json.loads(raw)
    if d['target']['width']!=480 or d['target']['height']!=800:raise ValueError('This template profile requires 480x800')
    values={'Width':480,'Height':800,'Margin':d['spacing']['page'],'Gutter':d['spacing']['gutter'],'ContentWidth':480-2*d['spacing']['page'],'Column':d['spacing']['column'],
      'ButtonRadius':d['radius']['button'],'CompactRadius':d['radius']['compact'],'ChoiceRadius':d['radius']['choice'],'KeyRadius':d['radius']['key'],'PanelRadius':d['radius']['card'],'HeroRadius':d['radius']['hero'],
      'Outline':d['stroke']['outline'],'Divider':d['stroke']['divider'],'GlyphStroke':d['stroke']['glyph'],'TouchMin':d['touch']['minimum'],'ButtonHeight':d['controls']['buttonHeight'],
      'BodyPx':d['typography']['body']['px'],'MetaPx':d['typography']['meta']['px'],'TitlePx':d['typography']['title']['px'],'CaptionPx':d['typography']['caption']['px'],'AnnotationPx':d['typography']['annotation']['px'],'HeroPx':d['typography']['hero']['px']}
    values.update({k[0].upper()+k[1:]:v for k,v in d['layout'].items()})
    assert values['Column']*2+values['Gutter']==values['ContentWidth']
    h='// Generated by tools/generate_ui_tokens.py. Edit design-tokens/effective-tokens.json.\n#pragma once\nnamespace paper { namespace ui { namespace token {\n'
    h+='inline constexpr const char* Schema = "PAPER-GLYPH-3";\ninline constexpr const char* SourceSha256 = "'+hashlib.sha256(raw).hexdigest()+'";\n'
    h+=''.join(f'inline constexpr int {k} = {v};\n'for k,v in values.items())
    h+='}}}\n';return h
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();out=ROOT/'components/paper_core/include/paper/generated/ui_tokens.hpp';want=expected()
    if a.check:
        if not out.exists() or out.read_text()!=want:raise SystemExit('UI token output is stale. Run tools/generate_ui_tokens.py; review the design change.')
        print('PASS: token source and C++ constants match')
    else:out.parent.mkdir(parents=True,exist_ok=True);out.write_text(want);print(out)
